#! /bin/sh
. ${HOME}/.cache/wal/colors.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width        3
bspc config window_gap          30
# bspc config top_padding         22

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle      true

bspc config normal_border_color "$background"
bspc config focused_border_color "$color4"
bspc config active_border_color "$color4"

bspc rule -a Gimp           desktop='^8'        state=tiled     follow=on
bspc rule -a firefox        desktop='^1'        follow=off
bspc rule -a "Tor Browser"  state=floating
bspc rule -a Zathura        state=tiled
bspc rule -a Steam          desktop='^7'
bspc rule -a qBittorrent    desktop='^10'
